{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c72cb5c0-3957-4718-83da-6428e1310060",
   "metadata": {},
   "outputs": [],
   "source": [
    "# src/pipeline.py\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "from sklearn.compose import ColumnTransformer, make_column_selector\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.experimental import enable_iterative_imputer\n",
    "from sklearn.impute import IterativeImputer\n",
    "from sklearn.preprocessing import RobustScaler, OneHotEncoder\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "\n",
    "\n",
    "class AdvancedDateEncoder(BaseEstimator, TransformerMixin):\n",
    "\n",
    "    def __init__(self, date_column=\"date\"):\n",
    "        self.date_column = date_column\n",
    "\n",
    "    def fit(self, X, y=None):\n",
    "        return self\n",
    "\n",
    "    def transform(self, X):\n",
    "        X = X.copy()\n",
    "        X[self.date_column] = pd.to_datetime(X[self.date_column])\n",
    "\n",
    "        X[\"month\"] = X[self.date_column].dt.month\n",
    "        X[\"dayofyear\"] = X[self.date_column].dt.dayofyear\n",
    "        X[\"quarter\"] = X[self.date_column].dt.quarter\n",
    "        X[\"dayofweek\"] = X[self.date_column].dt.dayofweek\n",
    "\n",
    "        X[\"month_sin\"] = np.sin(2 * np.pi * X[\"month\"] / 12)\n",
    "        X[\"month_cos\"] = np.cos(2 * np.pi * X[\"month\"] / 12)\n",
    "\n",
    "        X[\"dayofyear_sin\"] = np.sin(2 * np.pi * X[\"dayofyear\"] / 365)\n",
    "        X[\"dayofyear_cos\"] = np.cos(2 * np.pi * X[\"dayofyear\"] / 365)\n",
    "\n",
    "        X[\"is_weekend\"] = (X[\"dayofweek\"] >= 5).astype(int)\n",
    "        X[\"is_monsoon\"] = X[\"month\"].isin([6, 7, 8, 9]).astype(int)\n",
    "\n",
    "        return X.drop(columns=[self.date_column, \"month\", \"dayofyear\", \"dayofweek\"])\n",
    "\n",
    "\n",
    "def build_pipeline():\n",
    "\n",
    "    numeric_pipeline = Pipeline([\n",
    "        (\"imputer\", IterativeImputer()),\n",
    "        (\"scaler\", RobustScaler())\n",
    "    ])\n",
    "\n",
    "    categorical_pipeline = Pipeline([\n",
    "        (\"encoder\", OneHotEncoder(handle_unknown=\"ignore\"))\n",
    "    ])\n",
    "\n",
    "    model_pipeline = Pipeline([\n",
    "        (\"date_features\", AdvancedDateEncoder(date_column=\"date\")),\n",
    "        (\"preprocessing\", ColumnTransformer([\n",
    "            (\"num\", numeric_pipeline,\n",
    "             make_column_selector(dtype_include=np.number)),\n",
    "            (\"cat\", categorical_pipeline,\n",
    "             make_column_selector(dtype_exclude=np.number))\n",
    "        ], remainder=\"drop\")),\n",
    "        (\"model\", RandomForestRegressor(\n",
    "            n_estimators=300,\n",
    "            max_depth=8,\n",
    "            min_samples_split=5,\n",
    "            random_state=42\n",
    "        ))\n",
    "    ])\n",
    "\n",
    "    return model_pipeline"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (ML)",
   "language": "python",
   "name": "ml"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
